### ISSUE TITLE
Frax governance votes - Fibonacci: 8

### ISSUE THREAD

**Issue by IceCubeIIIIII** [LobisHQWorkspace/lobis-frontend#3]
**Scenario**
As a LOBI holder, I want to be able to see all governance votes for Frax and vote on them with my LOBI and sLOBI.

**Example**
Whenever a governance vote is posted on Frax governance, the vote should be replicated in a separated snapshot domain (example: Lobis_frax.eth) and holders should be able to vote until a certain date before the end of Frax vote (example: T - 1 hour). Then, at the end of the Lobis_frax vote, the bot should vote with the EOA which received the FXS vote delegation on Frax governance, proportionately to the LOBI votes.

Bonus: a discord notification could be sent when a new vote arrives.

Current draft (made by https://github.com/Maegner ):

https://docs.google.com/document/u/2/d/e/2PACX-1vQzzObUGNUEh6zSjrUBL856jlma41t0FHyeqKns6_C1a_q9i2JHVHyTfS2w_UeMBqUhklOdZSNjwhkQ/pub

Fibonacci: 8
Lobis: 2.5

Let's discuss on the next steps in this thread.

**Comment by Maegner** [comment]
https://github.com/Maegner/snapshot-duplicator
Implemented here
